#!/bin/bash

REPO_URL="git@github.com:Krio18/RayTracer.git"
INSTALL_DIR="RayTracer"

CRED='\033[5;31m'
LORANGE='\033[4m'
LIGHT_GREEN='\033[1;32m'
ORANGE='\033[1;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

#Status
error_exit()
{
    echo -e "${RED}[ERREUR] $1${RESET}" 1>&2
    exit 1
}

success()
{
    echo -e "${GREEN}[SUCCÈS] $1${RESET}"
}

work()
{
    echo -e "${ORANGE}[WORK] $1${ORANGE}"
}


#Instruction
build_project() {
    make || error_exit "La construction du projet a échoué."
    success "Projet construit avec succès."
}

update_repo() {
    if git pull | grep -q "Already up to date."; then
        success "Le dépôt est déjà à jour."
    else
        work "Dépôt mis à jour avec succès."
        build_project
    fi
    exit
}


delete_project() {
    echo ""
    read -p "Remove RayTracer [y/n]: " response
    echo ""
    if [[ "$response" == "y" || "$response" == "yes" || "$response" == "Y" || "$response" == "" ]]; then
        echo -e "Bye Bye RayTracer."
        echo ""
        cd "$(find / -name RayTracer 2>/dev/null -type d -print -quit)" || error_exit "Répertoire RayTracer non trouvé."
        cd ..
        rm -rf RayTracer
        echo "Success"
    elif [[ "$response" == "n" || "$response" == "no" || "$response" == "N" ]]; then
        echo "Nothing to do."
        echo ""
    else
        echo "Invalid response."
        echo ""
    fi
    exit
}

show_help() {
    echo "Usage: ./raytracer configs/<NOM_DU_FICHIER_DE_SCENE>"
    echo
    echo "Options:"
    echo "  -u        Met à jour le projet."
    echo "  -d        Supprime le projet."
    echo "  -h        Affiche cette aide."
    exit
}

if [[ $# -eq 0 ]]; then
    show_help
    exit 1
fi


#Action
while getopts "hud" option; do
    case $option in
        d)
            delete_project
            ;;
        u)
            update_repo
            ;;
        h)
            show_help
            ;;
        *)
            echo "Option inconnue: $1"
            show_help
            exit 1
            ;;
    esac
done

echo ""
cd "$(find / -name RayTracer 2>/dev/null -type d -print -quit)" || error_exit "Répertoire RayTracer non trouvé."
build_project
./raytracer "$@" > output.ppm
success "Construction de l'image terminer."
