#!/bin/bash

REPO_URL="git@github.com:Krio18/RayTracer.git"
INSTALL_DIR="RayTracer"

CRED='\033[5;31m'
LORANGE='\033[4m'
LIGHT_GREEN='\033[1;32m'
ORANGE='\033[1;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

error_exit() {
    echo -e "${RED}[ERREUR] $1${RESET}" 1>&2
    exit 1
}

success() {
    echo -e "${GREEN}[SUCCÈS] $1${RESET}"
}

build_project() {
    cd "$INSTALL_DIR" || error_exit "Impossible d'accéder au répertoire $INSTALL_DIR."
    make || error_exit "La construction du projet a échoué."
    success "Projet construit avec succès."
}

update_repo() {
    if [ -d "$INSTALL_DIR" ]; then
        cd "$INSTALL_DIR" || error_exit "Impossible d'accéder au répertoire $INSTALL_DIR."
        git pull || error_exit "Impossible de mettre à jour le dépôt."
        success "Dépôt mis à jour avec succès."
        build_project
    else
        error_exit "Le répertoire $INSTALL_DIR n'existe pas. Veuillez cloner le dépôt d'abord."
    fi
}

delete_project() {
    echo ""
    read -p "Remove RayTracer [y/n]: " response
    echo ""
    if [[ "$response" == "y" || "$response" == "yes" || "$response" == "Y" || "$response" == "" ]]; then
        echo -e "Bye Bye RayTracer."
        echo ""
        cd "$(find / -name RayTracer 2>/dev/null -type d -print -quit)" || error_exit "Répertoire RayTracer non trouvé."
        cd ..
        rm -rf RayTracer
        echo "Success"
    elif [[ "$response" == "n" || "$response" == "no" || "$response" == "N" ]]; then
        echo "Nothing to do."
        echo ""
    else
        echo "Invalid response."
        echo ""
    fi
    exit
}

show_help() {
    echo "Usage: $0 [OPTION]"
    echo
    echo "Options:"
    echo "  --install   Installe le projet"
    echo "  --update    Met à jour le projet"
    echo "  --delete    Supprime le projet"
    echo "  -h, --help  Affiche cette aide"
}

if [[ $# -eq 0 ]]; then
    show_help
    exit 1
fi

while getopts "hud" option; do
    case $option in
        d| --delete)
            delete_project
            ;;
        u| --update)
            update_repo
            ;;
        h|--help)
            show_help
            ;;
        *)
            build_project
            ;;
    esac
done

echo ""
cd "$(find / -name RayTracer 2>/dev/null -type d -print -quit)" || error_exit "Répertoire RayTracer non trouvé."
./raytracer "$@"
echo ""
